# Generated by Django 3.2.12 on 2022-02-27 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='status_tupla',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='motorista',
            name='status_tupla',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='status_tupla',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='viagem',
            name='status_tupla',
            field=models.BooleanField(default=True),
        ),
    ]
